import type { Metadata } from "next";
import { Cormorant_Garamond, Manrope } from "next/font/google";
import { CurrencyProvider } from "@/components/currency-context";
import { SITE_URL } from "@/lib/seo";
import "./globals.css";
import "./tropical-motion.css";

const sans=Manrope({subsets:["latin"],variable:"--font-sans"});
const serif=Cormorant_Garamond({subsets:["latin"],variable:"--font-serif",weight:["400","500","600"]});
export const metadata:Metadata={metadataBase:new URL(SITE_URL),title:{default:"Navigeto Travels | Sri Lanka & Worldwide Journeys",template:"%s | Navigeto Travels"},description:"Bespoke Sri Lanka holidays, international flights, hotels, private tours, transfers and visa support—beautifully connected by Navigeto Travels.",applicationName:"Navigeto Travels",creator:"Navigeto Travels",publisher:"Navigeto Travels",category:"travel",referrer:"origin-when-cross-origin",manifest:"/manifest.webmanifest",robots:{index:true,follow:true,googleBot:{index:true,follow:true,"max-image-preview":"large","max-snippet":-1,"max-video-preview":-1}},openGraph:{title:"Navigeto Travels | Travel, beautifully connected",description:"From Sri Lanka's beaches, hills and wildlife to worldwide journeys.",url:SITE_URL,type:"website",siteName:"Navigeto Travels",locale:"en_LK",images:[{url:"/og.png",width:1200,height:630,alt:"Navigeto Travels — travel, beautifully connected"}]},twitter:{card:"summary_large_image",title:"Navigeto Travels | Travel, beautifully connected",description:"Sri Lanka and the world, thoughtfully connected.",images:["/og.png"]}};
const structuredData={"@context":"https://schema.org","@graph":[{"@type":["Organization","TravelAgency"],"@id":`${SITE_URL}/#organization`,name:"Navigeto Travels",url:SITE_URL,logo:{"@type":"ImageObject",url:`${SITE_URL}/media/navigeto-logo.webp`},description:"Sri Lanka travel agency and destination management company offering hotels, private tours, transfers, flights, worldwide holidays and visa assistance.",address:{"@type":"PostalAddress",addressLocality:"Colombo",addressCountry:"LK"},email:"info@navigeto.com",telephone:"+94 77 420 6166",areaServed:[{"@type":"Country",name:"Sri Lanka"}]},{"@type":"WebSite","@id":`${SITE_URL}/#website`,url:SITE_URL,name:"Navigeto Travels",description:"Sri Lanka and worldwide journeys, beautifully connected.",publisher:{"@id":`${SITE_URL}/#organization`},inLanguage:"en"}]};
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang="en" className={`${sans.variable} ${serif.variable}`}><body><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/><CurrencyProvider>{children}</CurrencyProvider></body></html>}
