import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const palette = JSON.parse(readFileSync(new URL('../shared/brand/palette.json', import.meta.url), 'utf8'));
const declarations = Object.entries(palette).map(([name, value]) => {
  if (!/^#[0-9A-F]{6}$/.test(value)) throw new Error(`Invalid brand colour: ${name}`);
  return `  --brand-${name.replace(/[A-Z]/g, c => `-${c.toLowerCase()}`)}: ${value};`;
});
const css = `/* Generated by npm run brand:generate. Edit shared/brand/palette.json. */\n:root {\n${declarations.join('\n')}\n  --brand-signature: linear-gradient(90deg, var(--brand-blue) 0% 78%, var(--brand-green) 78% 94%, var(--brand-red) 94% 100%);\n}\n\n/* Opt-in signature: no positioning changes, no pointer-event interception. */\n.brand-signature.brand-signature {\n  background-image: var(--brand-signature);\n  background-size: 100% 3px;\n  background-position: left bottom;\n  background-repeat: no-repeat;\n}\n.brand-rule { height: 3px; background: var(--brand-signature); }\n.brand-accent-text { color: var(--brand-red); }\n.brand-accent-border { border-color: var(--brand-red); }\n`;
// This repository mirrors the Navigeto TravelOS brand palette.
const files = ['../shared/brand/tokens.css'];
for (const relative of files) {
  const file = fileURLToPath(new URL(relative, import.meta.url));
  if (process.argv.includes('--check')) {
    if (readFileSync(file, 'utf8') !== css) throw new Error(`Brand CSS is stale: ${relative}. Run npm run brand:generate.`);
  } else writeFileSync(file, css);
}
if (process.argv.includes('--check')) console.log('Brand tokens match the shared palette in every app.');
