import type { Metadata } from "next";
import { TourDetail } from "@/components/commerce-ui";
import { SiteShell } from "@/components/site-shell";
import { tours } from "@/lib/commerce-data";
import { liveApi } from "@/lib/live-api";
import { seoMetadata, SITE_URL } from "@/lib/seo";
export function generateStaticParams(){return tours.map(t=>({slug:t.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const tour=await liveApi.tour(slug).then(r=>r.result).catch(()=>null);const fallback=tours.find(item=>item.slug===slug);if(!tour&&!fallback)return seoMetadata(`/tours/package/${slug}`,{title:{absolute:"Tour not found | Navigeto Travels"},robots:{index:false,follow:false}});const title=tour?.title||fallback?.name||"Private Sri Lanka tour";const description=tour?.summary||`Explore the ${title} private journey and personalise its hotels, pace and experiences with Navigeto.`;return seoMetadata(`/tours/package/${slug}`,{title:{absolute:`${title} | Navigeto Travels`},description,openGraph:{title,description,url:`/tours/package/${slug}`,type:"website",images:tour?.hero_image_url?[{url:tour.hero_image_url,alt:title}]:[{url:"/og.png",alt:"Navigeto Travels"}]}});}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const tour=await liveApi.tour(slug).then(r=>r.result).catch(()=>null);const fallback=tours.find(item=>item.slug===slug);const schema=tour||fallback?{"@context":"https://schema.org","@type":"TouristTrip",name:tour?.title||fallback?.name,description:tour?.summary||`A private journey designed by Navigeto Travels.`,url:`${SITE_URL}/tours/package/${slug}`,image:tour?.hero_image_url||`${SITE_URL}/og.png`,touristType:tour?.tags||[fallback?.tag].filter(Boolean),itinerary:tour?.destinations?.map(name=>({"@type":"Place",name}))}:null;return <SiteShell>{schema?<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/>:null}<TourDetail slug={slug}/></SiteShell>}
