'use client';
/* eslint-disable @next/next/no-img-element -- Optimised catalogue assets are served from the approved image hosts. */
import { useState } from 'react';
import type { TransportCatalog, TransportMode } from './types';
import styles from './TransportPackages.module.css';
export type TransportSelection = { vehicleId: string; vehicle: string; mode: TransportMode; days: number; indicativeKm: number; sellingLkr: number; sellingUsd: number; version: string };
function VehiclePhoto({vehicle}:{vehicle:TransportCatalog['vehicles'][number]}) {
 const [selected,setSelected]=useState(0);
 const images=vehicle.gallery?.length?vehicle.gallery:[vehicle.image];
 return <><div className={styles.photo}><img src={images[selected]??images[0]} alt={`${vehicle.name} — ${selected===0?'exterior':'additional vehicle view'}, category example`} loading="lazy" width="600" height="400"/><span className={styles.imageLabel}>{vehicle.imageNote.includes('illustration')?'Representative illustration':'Vehicle category example'}</span></div>{images.length>1&&<div className={styles.gallery} aria-label={`${vehicle.name} photos`}>{images.map((src,i)=><button type="button" key={src} aria-label={`View ${vehicle.name} photo ${i+1}`} aria-pressed={selected===i} onClick={()=>setSelected(i)}><img src={src} alt="" loading="lazy" width="72" height="48"/></button>)}</div>}</>;
}
const money = (n: number) => n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
export function TransportPackages({catalog,onSelect}:{catalog:TransportCatalog;onSelect:(selection:TransportSelection)=>void}) {
  const [mode,setMode]=useState<TransportMode>('day');
  const [days,setDays]=useState('5');
  const [category,setCategory]=useState('All vehicles');
  const count=mode==='day'?1:Number(days);
  const valid=Number.isInteger(count)&&count>=1&&count<=60;
  return <section className={styles.wrap} aria-label="Transport packages">
    <header className={styles.header}><span className={styles.eyebrow}>Private Sri Lanka transport</span><h2>Your vehicle. Your route.<br/>A clear starting price.</h2><p>Compare day services and round-tour estimates in USD and LKR. Choose your preferred vehicle, share your itinerary and receive a final quotation before confirming.</p></header>
    <div className={styles.controls}><div className={styles.tabs} aria-label="Service type"><button type="button" aria-pressed={mode==='day'} onClick={()=>setMode('day')}>Day service · 100 km</button><button type="button" aria-pressed={mode==='round'} onClick={()=>setMode('round')}>Round tour · 190 km/day</button></div>{mode==='round'&&<label>Tour days<input type="number" min="1" max="60" value={days} onChange={e=>setDays(e.target.value)}/></label>}<label>Vehicle category<select value={category} onChange={e=>setCategory(e.target.value)}>{['All vehicles','Cars & vans','Coaches','Luxury'].map(c=><option key={c}>{c}</option>)}</select></label></div>
    <div className={styles.notice}><strong>{mode==='round'?'Planning estimate—not the final tour quotation.':'100 km day-service package.'}</strong> {mode==='round'?'We use 190 km per day to help you budget. After you finalise the itinerary, our team checks the actual route mileage and sends an accurate quote.':'Share the route and pickup time so we can verify the 100 km allowance and any extra mileage.'} Driver batta and driver accommodation are included. All prices are per vehicle, not per person. USD conversion: LKR {catalog.exchangeRate} = USD 1.</div>
    {!valid&&<p role="alert">Enter between 1 and 60 tour days.</p>}
    <div className={styles.grid}>{catalog.vehicles.filter(v=>category==='All vehicles'||v.category===category).map(v=>{
      const daily=mode==='day'?v.dayLkr:v.roundDayLkr;
      const lkr=valid?Math.round(daily*count*100)/100:0;
      const usd=Math.round(lkr/catalog.exchangeRate*100)/100;
      return <article className={styles.card} key={v.id}><VehiclePhoto vehicle={v}/><div className={styles.body}><span className={styles.eyebrow}>{v.category}</span><h3>{v.name}</h3><p>{v.description}</p><details><summary>Vehicle details & inclusions</summary><p>{v.imageNote}</p><ul><li>Private vehicle and chauffeur</li><li>{mode==='day'?100:190} km {mode==='day'?'day allowance':'per day used for estimating'}</li><li>Driver batta and accommodation included</li><li>Passenger and luggage capacity confirmed for your group</li></ul></details><div className={styles.price}><strong>{valid?`USD ${money(usd)}`:'Choose tour days'}</strong>{valid&&<><small>LKR {money(lkr)} · {mode==='day'?'one day':`${count}-day planning estimate`}</small>{mode==='round'&&<small>USD {money(daily/catalog.exchangeRate)} / day · {190*count} km estimated</small>}</>}</div><button className={styles.action} type="button" disabled={!valid} onClick={()=>onSelect({vehicleId:v.id,vehicle:v.name,mode,days:count,indicativeKm:(mode==='day'?100:190)*count,sellingLkr:lkr,sellingUsd:usd,version:catalog.version})}>Request quote & availability →</button></div></article>;
    })}</div>
    <section className={styles.terms} aria-label="Transport terms"><h3>From an estimate to a confirmed journey</h3><ol><li>Choose a vehicle and share dates, passengers, luggage and the full route.</li><li>We verify vehicle availability, itinerary mileage and any additional charges.</li><li>Review the final quote, payment schedule and cancellation terms, then confirm your booking.</li></ol><ul><li><strong>Round tours:</strong> 190 km/day is a budgeting basis only. The final itinerary may increase or reduce the quoted mileage and price.</li><li><strong>Included:</strong> the selected vehicle service, driver batta and LKR 5,000 driver accommodation allowance per operating day. Guest hotel rooms are not included.</li><li><strong>Confirm separately:</strong> tolls, parking, overtime, extra stops, excess mileage, entrance tickets, guest meals, child seats and applicable taxes. Any additions will be stated in the final quotation.</li><li><strong>Vehicle pictures:</strong> representative only. Vehicle model/year, seating, luggage space and requested features are confirmed before booking; no substitution without agreement.</li><li><strong>Availability and payment:</strong> a request or planning estimate does not reserve a vehicle. Written confirmation and the agreed payment are required. Changes and cancellations follow the terms in your final quote.</li><li><strong>Currency:</strong> displayed USD prices use LKR 310 per USD. Rounding is applied after calculating the total; the final quote specifies the payment currency and rate.</li></ul></section>
  </section>;
}
